title: Introduction to Linear Algebra

baseurl: /linear-algebra/

theme: minima

permalink: pretty

header_pages:
 - none

contents:
 - module: "1. Introduction"  
   nested:
   - section: "What is Linear Algebra ?"
     url: "1/introduction-to-linear-algebra"
 - module: "2. Vectors, Geometry, and Linear Combinations"
   nested:
   - section: "Vectors"
     url: "2/vectors"
   - section: "Vector Operations"
     url: "2/vector-operations"
   - section: "Self Assessment"
     url: "2/vector-operations"
 - module: "3. Matrices, Matrix Algebra, Row Reduction"
   nested:
   - section: "Matricies"
     url: "3/matricies-and-matrix-operations"
